owner: clann-inc
repo: tcm-upptime

sites:
  - name: prd
    url: https://hakubutsukan.city.toyota.aichi.jp/
  - name: stg
    url: https://hakubutsukan-stg.city.toyota.aichi.jp/
  - name: admin
    url: https://admin.hakubutsukan.city.toyota.aichi.jp/
  - name: kioku
    url: https://kioku.hakubutsukan.city.toyota.aichi.jp/
  - name: guide２
    url: https://guide.hakubutsukan.city.toyota.aichi.jp/

status-website:
  baseUrl: /tcm-upptime
  logoUrl: https://clann.werte.jp/wp-content/uploads/2020/07/logo.svg
  name: PRJ監視v1.1
  introTitle: ウェブサイト死活監視システム
  introMessage: 次のサイトの死活監視状況。5分毎にチェックしています。
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
